######################################################################
# Automatically generated by qmake (3.0) Sat Dec 31 19:35:52 2016
######################################################################

TEMPLATE = app
TARGET = 05.HelloWorld
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += gui widgets
